version: '3.8'

volumes:
  db:
  media:
  static:

services:
  db:
    build:
      context: .
      dockerfile: _compose/db/Dockerfile.prod
    volumes:
      - db:/var/lib/postgres/data
    ports:
      - '5454:5432'
    env_file:
      - _compose/env/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '35672:15672'

  celery-workers:
    env_file:
      - _compose/env/app
      - _compose/env/db
    command: /start-celery-workers
    volumes:
      - .:/app/code
    depends_on:
      - db
      - rabbitmq

  app:
    image: mnogo-ru-app
    command: /start-uvicorn
    build:
      context: .
      dockerfile: _compose/app/Dockerfile.prod
    depends_on:
      - db
      - redis
      - rabbitmq
      - celery-workers
    volumes:
      - .:/app/code
      - media:/app/code/media/media
      - static:/app/code/media/static
    expose:
      - 8000
    env_file:
      - _compose/env/app
  nginx:
    build:
      context: .
      dockerfile: ./_compose/nginx/Dockerfile
    restart: on-failure
    volumes:
      - media:/app/code/media/media
      - static:/app/code/media/static
    ports:
      - '1337:80'
    depends_on:
      - app